require:
  - standard

plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25
